!define abouturl "http://..."
!define appexe "Sjakk.exe"
!define appname "Sjakk"
!define description "A chess interface for FICS (freechess.org)"
!define helpurl "http://..."
!define installsize "1471531670"
!define licensetxt "license.txt"
!define logoico "sjakk.ico"
!define orgdomain "snorkelbuckle.net"
!define orgname "SnorkelBuckle"
!define updateurl "http://..."
!define versionbuild "19"
!define versionmajor "0"
!define versionminor "1"
!define versionyear "2019"
